### ISSUE TITLE
linux fonts not working

### ISSUE THREAD

**Issue by mehmet-erdogdu** [aliasadidev/SixLaborsCaptcha#11]
SixLabors.Fonts.FontFamilyNotFoundException: 'The "Ariel" font family could not be found in the following directories:
 * /usr/local/share/fonts/
 * /usr/share/fonts/'

Install cabextract, a tool needed to unpack self-extracting .exe archives:

sudo apt install cabextract
Download the font package provided via [this page](https://www.freedesktop.org/software/fontconfig/webfonts/) (also note the EULA there):

wget https://www.freedesktop.org/software/fontconfig/webfonts/webfonts.tar.gz
Unpack, twice:

tar -xzf webfonts.tar.gz
cd msfonts/
cabextract *.exe
Move the fonts to your user's directory for installing additional fonts:

cp *.ttf *.TTF ~/.local/share/fonts/

cp *.ttf *.TTF /usr/local/share/fonts/

https://askubuntu.com/a/1092920

**Comment by aliasadidev** [comment]
This is not related to the font issue, I didn't install cabextract
```sh
wget https://www.freebestfonts.com/yone//down/arial.ttf
sudo mv arial.ttf  /usr/share/fonts/
```
```c#
var slc = new SixLaborsCaptchaModule(new SixLaborsCaptchaOptions
      {
        DrawLines = 5,
        TextColor = new Color[] { Color.Gray },
        DrawLinesColor = new Color[] { Color.Gray, Color.Black, Color.DarkGrey, Color.SlateGray },
        FontFamilies = new string[] { "arial" },
      });
```
![six-labors-captcha-0](https://user-images.githubusercontent.com/6399165/205291660-5b2ece8e-015c-4919-b6d5-00cb9dc98d63.png)
