### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by naviti** [aliasadidev/SixLaborsCaptcha#5]
After a project upgrade from .net5 to .net6 and an upgrade to the latest SixLabors.ImageSharp version 2.1.0 (which is needed for my project) the library does not seem to work anymore. I get the following exception:

MissingMethodException: Method not found: 'System.Span`1<SixLabors.ImageSharp.PixelFormats.Rgba32> SixLabors.ImageSharp.Memory.Buffer2D`1.GetRowSpan(Int32)'.

Do you have any plans to upgrade your project anytime soon in order to work with the latest SixLabors.ImageSharp version?
Thank you very much!

**Comment by aliasadidev** [comment]
Hi @naviti 
Thanks for reporting, I will check it.

**Comment by aliasadidev** [comment]
I upgraded SixLabors.ImageSharp to 2.1.1, you can test it in version 0.2.0.
I'm looking forward to your tests.
@naviti 
@artmedia

**Comment by naviti** [comment]
Works perfectly, thank you very much!!

**Comment by artmedia** [comment]
great, thanks
