### ISSUE TITLE
Happens after multiple generate: 'minValue' cannot be greater than maxValue

### ISSUE THREAD

**Issue by SmRiley** [aliasadidev/SixLaborsCaptcha#9]
I thought it was because of the Blazor scope problem at first, and I also had this problem after replacing MVC with Core.
![image](https://user-images.githubusercontent.com/45205313/192185864-260f8af6-3aa3-4de3-974a-a87cfab17ed1.png)

**Comment by SmRiley** [comment]
The number of times is not fixed, it may be a dozen times, or hundreds of times.
![1664169124844](https://user-images.githubusercontent.com/45205313/192198544-2ee72974-580d-4dd6-9360-40f3122d2c6d.gif)

**Comment by aliasadidev** [comment]
Hi @SmRiley 
You're right. I fixed
#10
